### PR TITLE
added log out page

### PR DESCRIPTION
**Pull request by rohanmathur91**
## Description:
 - Added log out page

## Screenshot:
image

### CODE REVIEW

**Review by prakashsakari — APPROVED** [review]
Looks good to me

**Review by Naveenchandar — COMMENTED** [review]
Is Logout screen necessary ? Can't we redirect to login after on click of logout ?.

**Comment by rohanmathur91** [comment]
> Is Logout screen necessary ? Can't we redirect to login after on click of logout ?.

Its mention that we need logout on lms.

**Review by Naveenchandar — APPROVED** [review]
Looks good

**Pull request merged**
