### PR TITLE
updated address management

### PR DESCRIPTION
**Pull request by rohanmathur91**
## Description:
 - Added more fields to address the form
 - Created address listing page

## Screenshot:
image
image

### CODE REVIEW

**Review by aurobindoGupta — APPROVED** [review]
good work!!

**Review by ianuragsharma — APPROVED** [review]
Clean and crisp code,good to merge.

**Review by Aditi0505 — APPROVED** [review]
Looks good to me!

**Review by ckahub — COMMENTED** [review]
looks clean and good spacing
good to merge

**Pull request merged**
